"""3주차 Decision Tree 교재용 PNG를 재현 생성합니다.

`03주차/example.ipynb`와 동일하게 로컬 따릉이 일별 데이터를 모두 읽고,
마지막 60일을 홀드아웃으로 사용합니다. 실행 위치와 관계없이 저장 결과는
이 스크립트가 있는 `assets/` 디렉터리에 기록됩니다.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.dates as mdates
import matplotlib.font_manager as font_manager
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error
from sklearn.tree import DecisionTreeRegressor, plot_tree


RANDOM_STATE = 42
HOLDOUT_DAYS = 60
ASSET_DIR = Path(__file__).resolve().parent
REPO_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = (
    REPO_ROOT
    / "dataset"
    / "extracted"
    / "따릉이 공공데이터"
    / "02_이용정보"
)
DATA_PATTERN = "서울특별시 공공자전거 일별 대여건수_*.csv"


def configure_plotting() -> None:
    """한국어 글꼴과 공통 렌더링 설정을 고정합니다."""

    available = {font.name for font in font_manager.fontManager.ttflist}
    for candidate in ("Malgun Gothic", "Noto Sans CJK KR", "NanumGothic"):
        if candidate in available:
            plt.rcParams["font.family"] = candidate
            break
    plt.rcParams["axes.unicode_minus"] = False
    plt.rcParams["figure.facecolor"] = "white"
    plt.rcParams["savefig.facecolor"] = "white"
    np.random.seed(RANDOM_STATE)


def load_bike_data() -> tuple[pd.DataFrame, pd.DataFrame, pd.Series, int]:
    """노트북과 같은 전처리로 날짜순 X, y와 분할 위치를 반환합니다."""

    files = sorted(DATA_DIR.glob(DATA_PATTERN))
    if not files:
        raise FileNotFoundError(f"따릉이 CSV를 찾을 수 없습니다: {DATA_DIR / DATA_PATTERN}")

    frames = [pd.read_csv(path, encoding="cp949") for path in files]
    df = pd.concat(frames, ignore_index=True)
    required = {"대여일자", "대여건수"}
    missing = required.difference(df.columns)
    if missing:
        raise ValueError(f"필수 열이 없습니다: {sorted(missing)}")

    df["대여일자"] = pd.to_datetime(df["대여일자"])
    df = df.sort_values("대여일자").reset_index(drop=True)
    if len(df) <= HOLDOUT_DAYS:
        raise ValueError(f"최소 {HOLDOUT_DAYS + 1}개 행이 필요합니다: {len(df)}개")

    df["day_index"] = (df["대여일자"] - df["대여일자"].min()).dt.days
    df["월"] = df["대여일자"].dt.month
    df["요일"] = df["대여일자"].dt.day_name()

    month_dummies = pd.get_dummies(df["월"], prefix="월", drop_first=True)
    weekday_dummies = pd.get_dummies(df["요일"], prefix="요일", drop_first=True)
    X = pd.concat([df[["day_index"]], month_dummies, weekday_dummies], axis=1)
    y = df["대여건수"]
    split_idx = len(df) - HOLDOUT_DAYS
    return df, X, y, split_idx


def save_figure(fig: plt.Figure, filename: str) -> None:
    """고정 해상도로 PNG를 저장하고 figure를 닫습니다."""

    output = ASSET_DIR / filename
    fig.savefig(
        output,
        dpi=180,
        bbox_inches="tight",
        facecolor="white",
        metadata={"Software": "Matplotlib; generated by 03주차/assets/generate_assets.py"},
    )
    plt.close(fig)
    print(f"생성: {output.relative_to(REPO_ROOT)}")


def make_toy_tree() -> None:
    """Part 1의 간단한 예제인 깊이 2 회귀 트리를 생성합니다."""

    toy = pd.DataFrame(
        {
            "기온": [5, 10, 15, 20, 25, 30],
            "판매량": [20, 35, 40, 55, 70, 90],
        }
    )
    model = DecisionTreeRegressor(max_depth=2, random_state=RANDOM_STATE)
    model.fit(toy[["기온"]], toy["판매량"])

    fig, ax = plt.subplots(figsize=(9, 5), constrained_layout=True)
    plot_tree(
        model,
        feature_names=["기온"],
        filled=True,
        rounded=True,
        precision=2,
        ax=ax,
        fontsize=9,
    )
    ax.set_title("회귀 트리 예제: 기온으로 아이스크림 판매량 예측", pad=12)
    save_figure(fig, "decision_tree_toy.png")


def make_bike_figures() -> None:
    """실제 따릉이 데이터 기반 그림 3개와 검증 지표를 생성합니다."""

    df, X, y, split_idx = load_bike_data()
    X_train, X_test = X.iloc[:split_idx], X.iloc[split_idx:]
    y_train, y_test = y.iloc[:split_idx], y.iloc[split_idx:]

    linear_model = LinearRegression().fit(X_train, y_train)
    tree_full = DecisionTreeRegressor(random_state=RANDOM_STATE).fit(X_train, y_train)
    tree_pruned = DecisionTreeRegressor(
        max_depth=6,
        min_samples_leaf=20,
        random_state=RANDOM_STATE,
    ).fit(X_train, y_train)

    rmse_linear = root_mean_squared_error(y_test, linear_model.predict(X_test))
    rmse_full_train = root_mean_squared_error(y_train, tree_full.predict(X_train))
    rmse_full_test = root_mean_squared_error(y_test, tree_full.predict(X_test))
    rmse_pruned_train = root_mean_squared_error(y_train, tree_pruned.predict(X_train))
    rmse_pruned_test = root_mean_squared_error(y_test, tree_pruned.predict(X_test))

    tree_for_viz = DecisionTreeRegressor(
        max_depth=3,
        random_state=RANDOM_STATE,
    ).fit(X_train, y_train)
    fig, ax = plt.subplots(figsize=(18, 8), constrained_layout=True)
    plot_tree(
        tree_for_viz,
        feature_names=list(X.columns),
        filled=True,
        rounded=True,
        precision=1,
        ax=ax,
        fontsize=8,
    )
    ax.set_title("따릉이 대여량 예측을 위한 깊이 3 Decision Tree", pad=12)
    save_figure(fig, "bike_tree_depth3.png")

    importances = pd.Series(
        tree_pruned.feature_importances_, index=X.columns
    ).sort_values(ascending=False)
    top_importances = importances.head(10).sort_values(ascending=True)
    fig, ax = plt.subplots(figsize=(8, 5.5), constrained_layout=True)
    ax.barh(top_importances.index, top_importances.values, color="#4C78A8")
    ax.set_xlabel("불순도 감소 기반 중요도(MDI)")
    ax.set_title("Decision Tree 변수 중요도 상위 10개")
    ax.grid(axis="x", alpha=0.25)
    save_figure(fig, "decision_tree_feature_importance.png")

    holdout_dates = df["대여일자"].iloc[split_idx:]
    fig, ax = plt.subplots(figsize=(11, 5), constrained_layout=True)
    ax.plot(holdout_dates, y_test.to_numpy(), label="실제", linewidth=2.2, color="#222222")
    ax.plot(
        holdout_dates,
        linear_model.predict(X_test),
        label=f"선형회귀 (RMSE {rmse_linear:,.0f})",
        linewidth=1.8,
        color="#E45756",
    )
    ax.plot(
        holdout_dates,
        tree_pruned.predict(X_test),
        label=f"가지치기 트리 (RMSE {rmse_pruned_test:,.0f})",
        linewidth=1.8,
        color="#4C78A8",
    )
    ax.set_title("마지막 60일: 실제 대여량과 모델 예측")
    ax.set_xlabel("대여일자")
    ax.set_ylabel("대여건수")
    ax.xaxis.set_major_locator(mdates.AutoDateLocator(minticks=5, maxticks=8))
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y-%m-%d"))
    ax.tick_params(axis="x", rotation=30)
    ax.grid(alpha=0.22)
    ax.legend()
    save_figure(fig, "bike_predictions_linear_vs_tree.png")

    print(f"데이터 행: {len(df):,}, 학습/홀드아웃: {len(X_train):,}/{len(X_test):,}")
    print(f"선형회귀 홀드아웃 RMSE: {rmse_linear:,.6f}")
    print(f"제한 없는 트리 train/홀드아웃 RMSE: {rmse_full_train:,.6f} / {rmse_full_test:,.6f}")
    print(f"가지치기 트리 train/홀드아웃 RMSE: {rmse_pruned_train:,.6f} / {rmse_pruned_test:,.6f}")


def main() -> None:
    configure_plotting()
    make_toy_tree()
    make_bike_figures()


if __name__ == "__main__":
    main()
