"""4주차 Random Forest 교재용 PNG를 재현 생성합니다.

`04주차/example.ipynb`와 동일하게 로컬 따릉이 일별 데이터를 모두 읽고,
마지막 60일을 홀드아웃으로 사용합니다. 현재 노트북의 기본 동작을 버전 간에
고정하기 위해 `max_features=1.0`과 `n_jobs=1`을 명시합니다.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.dates as mdates
import matplotlib.font_manager as font_manager
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error
from sklearn.tree import DecisionTreeRegressor, export_text


RANDOM_STATE = 42
HOLDOUT_DAYS = 60
ASSET_DIR = Path(__file__).resolve().parent
REPO_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = (
    REPO_ROOT
    / "dataset"
    / "extracted"
    / "따릉이 공공데이터"
    / "02_이용정보"
)
DATA_PATTERN = "서울특별시 공공자전거 일별 대여건수_*.csv"


def configure_plotting() -> None:
    """한국어 글꼴과 공통 렌더링 설정을 고정합니다."""

    available = {font.name for font in font_manager.fontManager.ttflist}
    for candidate in ("Malgun Gothic", "Noto Sans CJK KR", "NanumGothic"):
        if candidate in available:
            plt.rcParams["font.family"] = candidate
            break
    plt.rcParams["axes.unicode_minus"] = False
    plt.rcParams["figure.facecolor"] = "white"
    plt.rcParams["savefig.facecolor"] = "white"
    np.random.seed(RANDOM_STATE)


def load_bike_data() -> tuple[pd.DataFrame, pd.DataFrame, pd.Series, int]:
    """노트북과 같은 전처리로 날짜순 X, y와 분할 위치를 반환합니다."""

    files = sorted(DATA_DIR.glob(DATA_PATTERN))
    if not files:
        raise FileNotFoundError(f"따릉이 CSV를 찾을 수 없습니다: {DATA_DIR / DATA_PATTERN}")

    frames = [pd.read_csv(path, encoding="cp949") for path in files]
    df = pd.concat(frames, ignore_index=True)
    required = {"대여일자", "대여건수"}
    missing = required.difference(df.columns)
    if missing:
        raise ValueError(f"필수 열이 없습니다: {sorted(missing)}")

    df["대여일자"] = pd.to_datetime(df["대여일자"])
    df = df.sort_values("대여일자").reset_index(drop=True)
    if len(df) <= HOLDOUT_DAYS:
        raise ValueError(f"최소 {HOLDOUT_DAYS + 1}개 행이 필요합니다: {len(df)}개")

    df["day_index"] = (df["대여일자"] - df["대여일자"].min()).dt.days
    df["월"] = df["대여일자"].dt.month
    df["요일"] = df["대여일자"].dt.day_name()

    month_dummies = pd.get_dummies(df["월"], prefix="월", drop_first=True)
    weekday_dummies = pd.get_dummies(df["요일"], prefix="요일", drop_first=True)
    X = pd.concat([df[["day_index"]], month_dummies, weekday_dummies], axis=1)
    y = df["대여건수"]
    split_idx = len(df) - HOLDOUT_DAYS
    return df, X, y, split_idx


def save_figure(fig: plt.Figure, filename: str) -> None:
    """고정 해상도로 PNG를 저장하고 figure를 닫습니다."""

    output = ASSET_DIR / filename
    fig.savefig(
        output,
        dpi=180,
        bbox_inches="tight",
        facecolor="white",
        metadata={"Software": "Matplotlib; generated by 04주차/assets/generate_assets.py"},
    )
    plt.close(fig)
    print(f"생성: {output.relative_to(REPO_ROOT)}")


def print_toy_stability_check() -> None:
    """Part 1의 텍스트 출력 실험을 같은 시드로 재현합니다."""

    toy = pd.DataFrame(
        {
            "기온": [5, 10, 15, 20, 25, 30],
            "판매량": [20, 35, 40, 55, 70, 90],
        }
    )
    toy_drop = toy.drop(index=3)
    tree_all = DecisionTreeRegressor(
        max_depth=2, random_state=RANDOM_STATE
    ).fit(toy[["기온"]], toy["판매량"])
    tree_drop = DecisionTreeRegressor(
        max_depth=2, random_state=RANDOM_STATE
    ).fit(toy_drop[["기온"]], toy_drop["판매량"])
    rf_all = RandomForestRegressor(
        n_estimators=100,
        max_depth=2,
        max_features=1.0,
        random_state=RANDOM_STATE,
        n_jobs=1,
    ).fit(toy[["기온"]], toy["판매량"])
    rf_drop = RandomForestRegressor(
        n_estimators=100,
        max_depth=2,
        max_features=1.0,
        random_state=RANDOM_STATE,
        n_jobs=1,
    ).fit(toy_drop[["기온"]], toy_drop["판매량"])
    query = pd.DataFrame({"기온": [22]})

    print("전체 6개로 학습한 트리 규칙:")
    print(export_text(tree_all, feature_names=["기온"]))
    print("점 1개를 뺀 5개로 학습한 트리 규칙:")
    print(export_text(tree_drop, feature_names=["기온"]))
    print(f"전체 데이터 단일 트리 예측(기온=22): {tree_all.predict(query)[0]:.6f}")
    print(f"점 1개 제외 단일 트리 예측(기온=22): {tree_drop.predict(query)[0]:.6f}")
    print(f"전체 데이터 RF 예측(기온=22): {rf_all.predict(query)[0]:.6f}")
    print(f"점 1개 제외 RF 예측(기온=22): {rf_drop.predict(query)[0]:.6f}")


def make_bike_figures() -> None:
    """실제 따릉이 데이터 기반 그림 2개와 검증 지표를 생성합니다."""

    df, X, y, split_idx = load_bike_data()
    X_train, X_test = X.iloc[:split_idx], X.iloc[split_idx:]
    y_train, y_test = y.iloc[:split_idx], y.iloc[split_idx:]

    linear_model = LinearRegression().fit(X_train, y_train)
    tree_model = DecisionTreeRegressor(
        max_depth=6,
        min_samples_leaf=20,
        random_state=RANDOM_STATE,
    ).fit(X_train, y_train)
    rf_model = RandomForestRegressor(
        n_estimators=100,
        max_depth=6,
        min_samples_leaf=10,
        max_features=1.0,
        random_state=RANDOM_STATE,
        n_jobs=1,
    ).fit(X_train, y_train)

    rmse_linear = root_mean_squared_error(y_test, linear_model.predict(X_test))
    rmse_tree = root_mean_squared_error(y_test, tree_model.predict(X_test))
    rmse_rf_train = root_mean_squared_error(y_train, rf_model.predict(X_train))
    rmse_rf_test = root_mean_squared_error(y_test, rf_model.predict(X_test))

    importance_compare = pd.DataFrame(
        {
            "단일 트리": tree_model.feature_importances_,
            "Random Forest": rf_model.feature_importances_,
        },
        index=X.columns,
    ).sort_values("Random Forest", ascending=False)
    top = importance_compare.head(10).iloc[::-1]
    positions = np.arange(len(top))
    height = 0.38
    fig, ax = plt.subplots(figsize=(9, 6), constrained_layout=True)
    ax.barh(
        positions - height / 2,
        top["단일 트리"],
        height=height,
        label="단일 트리",
        color="#F58518",
    )
    ax.barh(
        positions + height / 2,
        top["Random Forest"],
        height=height,
        label="Random Forest",
        color="#4C78A8",
    )
    ax.set_yticks(positions, labels=top.index)
    ax.set_xlabel("불순도 감소 기반 중요도(MDI)")
    ax.set_title("단일 트리와 Random Forest 변수 중요도 비교")
    ax.grid(axis="x", alpha=0.25)
    ax.legend()
    save_figure(fig, "feature_importance_tree_vs_rf.png")

    holdout_dates = df["대여일자"].iloc[split_idx:]
    fig, ax = plt.subplots(figsize=(11, 5), constrained_layout=True)
    ax.plot(holdout_dates, y_test.to_numpy(), label="실제", linewidth=2.2, color="#222222")
    ax.plot(
        holdout_dates,
        linear_model.predict(X_test),
        label=f"선형회귀 (RMSE {rmse_linear:,.0f})",
        linewidth=1.7,
        color="#E45756",
    )
    ax.plot(
        holdout_dates,
        tree_model.predict(X_test),
        label=f"단일 트리 (RMSE {rmse_tree:,.0f})",
        linewidth=1.7,
        color="#F58518",
    )
    ax.plot(
        holdout_dates,
        rf_model.predict(X_test),
        label=f"Random Forest (RMSE {rmse_rf_test:,.0f})",
        linewidth=1.7,
        color="#4C78A8",
    )
    ax.set_title("마지막 60일: 실제 대여량과 세 모델 예측")
    ax.set_xlabel("대여일자")
    ax.set_ylabel("대여건수")
    ax.xaxis.set_major_locator(mdates.AutoDateLocator(minticks=5, maxticks=8))
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y-%m-%d"))
    ax.tick_params(axis="x", rotation=30)
    ax.grid(alpha=0.22)
    ax.legend()
    save_figure(fig, "bike_predictions_three_models.png")

    print(f"데이터 행: {len(df):,}, 학습/홀드아웃: {len(X_train):,}/{len(X_test):,}")
    print(f"선형회귀 홀드아웃 RMSE: {rmse_linear:,.6f}")
    print(f"가지치기 단일 트리 홀드아웃 RMSE: {rmse_tree:,.6f}")
    print(f"Random Forest train/홀드아웃 RMSE: {rmse_rf_train:,.6f} / {rmse_rf_test:,.6f}")


def main() -> None:
    configure_plotting()
    print_toy_stability_check()
    make_bike_figures()


if __name__ == "__main__":
    main()
